FROM bellsoft/hardened-liberica-runtime-container:jdk-25-musl AS builder

WORKDIR /workspace

COPY ../pom.xml mvnw ./
COPY ../.mvn .mvn
RUN chmod +x mvnw
COPY ../src src


RUN ./mvnw package \
     && cp target/med-flow-*.jar application.jar

RUN mkdir /workspace/extracted \
    && java -Djarmode=tools \
       -jar application.jar \
       extract \
       --layers \
       --destination /workspace/extracted


FROM bellsoft/hardened-liberica-runtime-container:jre-25-nonroot-musl AS trainer

WORKDIR /application

COPY --from=builder /workspace/extracted/dependencies/ ./
COPY --from=builder /workspace/extracted/spring-boot-loader/ ./
COPY --from=builder /workspace/extracted/snapshot-dependencies/ ./
COPY --from=builder /workspace/extracted/application/ ./

RUN java \
    -Dspring.profiles.active=aot \
    -XX:AOTCacheOutput=/tmp/app.aot \
    -Dspring.context.exit=onRefresh \
    -jar application.jar


FROM bellsoft/hardened-liberica-runtime-container:jre-25-nonroot-musl

WORKDIR /application

COPY --from=builder /workspace/extracted/dependencies/ ./
COPY --from=builder /workspace/extracted/spring-boot-loader/ ./
COPY --from=builder /workspace/extracted/snapshot-dependencies/ ./
COPY --from=builder /workspace/extracted/application/ ./

COPY --from=trainer /tmp/app.aot ./app.aot

EXPOSE 8080

ENTRYPOINT ["java", "-XX:AOTCache=app.aot", "-jar", "application.jar"]